### PR TITLE
Removed lodash methods

### PR DESCRIPTION
**Pull request by kishorevarma**
Hi,

Because of reduce and isFunction methods the file size increased to 83.64 kb, after removing it came down to 1.56kb.

Thanks
Kishore

### CODE REVIEW

**Comment by tomatau** [comment]
Wahey! I was hoping no-one would notice I used the lodash methods :P That was literally me being very lazy as I use lodash all the time anyway so doesn't affect my bundle size :))

Thanks for this PR! Could you remove the package.json dependency as well please and then I'm very happy to merge, bump and release.

**Comment by tomatau** [comment]
Magic thanks! I'll release this within the next 24 hours when I get home from work and play.

**Comment by kishorevarma** [comment]
cheers @tomatau

**Comment by tomatau** [comment]
released `type-to-reducer@1.0.2`

**Comment by kishorevarma** [comment]
Thanks @tomatau

**Pull request merged**
